name: Build UnityExplorer

# Controls when the action will run.
on:
  push:
    branches: [master]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    if: "!contains(github.event.head_commit.message, '-noci')"

    steps:
      # Setup

      - name: Checkout latest
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.x'
      # Run build script
      - name: Build UE
        run: ./build.ps1

      #  Upload artifacts
      - name: Upload BepInEx.IL2CPP
        uses: actions/upload-artifact@v4
        with:
          name: UnityExplorer.BepInEx.IL2CPP
          path: ./Release/UnityExplorer.BepInEx.IL2CPP/

      - name: Upload BepInEx.IL2CPP.CoreCLR
        uses: actions/upload-artifact@v4
        with:
          name: UnityExplorer.BepInEx.IL2CPP.CoreCLR
          path: ./Release/UnityExplorer.BepInEx.IL2CPP.CoreCLR/

      - name: Upload BepInEx.Unity.IL2CPP.CoreCLR
        uses: actions/upload-artifact@v4
        with:
          name: UnityExplorer.BepInEx.Unity.IL2CPP.CoreCLR
          path: ./Release/UnityExplorer.BepInEx.Unity.IL2CPP.CoreCLR/

      - name: Upload BepInEx5.Mono
        uses: actions/upload-artifact@v4
        with:
          name: UnityExplorer.BepInEx5.Mono
          path: ./Release/UnityExplorer.BepInEx5.Mono/

      - name: Upload BepInEx6.Mono
        uses: actions/upload-artifact@v4
        with:
          name: UnityExplorer.BepInEx6.Mono
          path: ./Release/UnityExplorer.BepInEx6.Mono/

      - name: Upload BepInEx6.Unity.Mono
        uses: actions/upload-artifact@v4
        with:
          name: UnityExplorer.BepInEx6.Unity.Mono
          path: ./Release/UnityExplorer.BepInEx6.Unity.Mono/

      - name: Upload MelonLoader.IL2CPP
        uses: actions/upload-artifact@v4
        with:
          name: UnityExplorer.MelonLoader.IL2CPP
          path: ./Release/UnityExplorer.MelonLoader.IL2CPP/

      - name: Upload MelonLoader.IL2CPP.net6preview
        uses: actions/upload-artifact@v4
        with:
          name: UnityExplorer.MelonLoader.IL2CPP.net6preview
          path: ./Release/UnityExplorer.MelonLoader.IL2CPP.net6preview/

      - name: Upload MelonLoader.IL2CPP.CoreCLR
        uses: actions/upload-artifact@v4
        with:
          name: UnityExplorer.MelonLoader.IL2CPP.CoreCLR
          path: ./Release/UnityExplorer.MelonLoader.IL2CPP.CoreCLR/

      - name: Upload MelonLoader.Mono
        uses: actions/upload-artifact@v4
        with:
          name: UnityExplorer.MelonLoader.Mono
          path: ./Release/UnityExplorer.MelonLoader.Mono/

      - name: Upload Standalone.IL2CPP
        uses: actions/upload-artifact@v4
        with:
          name: UnityExplorer.Standalone.IL2CPP
          path: ./Release/UnityExplorer.Standalone.IL2CPP/

      - name: Upload Standalone.IL2CPP.CoreCLR
        uses: actions/upload-artifact@v4
        with:
          name: UnityExplorer.Standalone.IL2CPP.CoreCLR
          path: ./Release/UnityExplorer.Standalone.IL2CPP.CoreCLR/

      - name: Upload Standalone.Mono
        uses: actions/upload-artifact@v4
        with:
          name: UnityExplorer.Standalone.Mono
          path: ./Release/UnityExplorer.Standalone.Mono/

      - name: Upload Editor
        uses: actions/upload-artifact@v4
        with:
          name: UnityExplorer.Editor
          path: ./UnityEditorPackage/
